services:
  mysql:
    image: mysql:8.0
    container_name: kibaauth_database
    restart: unless-stopped
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kibaauth
      MYSQL_USER: kibaauth_user
      MYSQL_PASSWORD: kibaauth_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local
